defaults:
  - _self_

method: semi-supervised-ensemble

train:
  total_epochs: 250
  validation_interval: 5
  alpha: 0.995 # between 0.9 and 0.999 makes sense
  unlabeled_per_labeled: 1 # can only be 0, 1, 2, 3 or 4 (0 meaning no unlabeled data)

init:
  _target_: trainer.MeanTeacherEnsemble
  supervised_criterion:
    _target_: torch.nn.MSELoss
  unsupervised_criterion:
    _target_: torch.nn.MSELoss
  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 0.008019380847234798
    weight_decay: 0.0068404540674212744
  scheduler:
    _target_: torch.optim.lr_scheduler.StepLR
    _partial_: true
    step_size: 1
    gamma: 0.9899584023212821

    